language: python
python:
        - "2.7"

# command to install dependencies
install: "pip install -r cmput404project/requirements.txt"

# command to run tests
script: 
        - cd cmput404project
        - python manage.py test
