# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 21:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iden', models.UUIDField()),
                ('host', models.CharField(default=b'')),
                ('image', models.CharField(default=b'')),
            ],
        ),
    ]
