# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=30)),
                ('displayName', models.CharField(max_length=30)),
            ],
        ),
    ]
