# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[(b'PUBLIC', b'PUBLIC'), (b'PRIVATE', b'PRIVATE'), (b'FRIENDS', b'FRIENDS'), (b'FOAF', b'FOAF'), (b'SERVERONLY', b'SERVERONLY')], default=b'PUBLIC', max_length=1),
        ),
    ]
