# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='size',
            field=models.IntegerField(default=50),
        ),
    ]
