# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pubDate',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
