# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pubDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
