# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='unique_id',
            new_name='id',
        ),
    ]
