# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='port',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
