# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20161104_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='service.Author'),
        ),
    ]
