# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20161122_2338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NodeManager',
        ),
        migrations.AlterField(
            model_name='node',
            name='path',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
