# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20161031_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_type',
        ),
        migrations.AddField(
            model_name='post',
            name='contentType',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
