# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20161119_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='node',
            name='user',
        ),
    ]
