# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20161031_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='published',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(default=b'text/plain', editable=False, max_length=100),
        ),
    ]
