# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20161104_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
