# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_comment_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(default=b'text/plain', max_length=100),
        ),
    ]
