# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20161102_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='host',
            field=models.CharField(default=b'127.0.0.1:8000', max_length=100),
        ),
    ]
