# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20161126_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='next',
        ),
        migrations.RemoveField(
            model_name='post',
            name='size',
        ),
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[(b'text/plain', b'text/plain'), (b'text/markdown', b'text/markdown')], default=b'text/plain', max_length=100),
        ),
    ]
