# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20161030_0327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('A_id',)},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='id',
            new_name='A_id',
        ),
    ]
