# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20161101_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('id',)},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='A_id',
            new_name='id',
        ),
    ]
