# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20161102_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[(b'PU', b'PUBLIC'), (b'PR', b'PRIVATE'), (b'FR', b'FRIENDS'), (b'FO', b'FOAF'), (b'SO', b'SERVERONLY')], default=b'PUBLIC', max_length=10),
        ),
    ]
