# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20161127_2054'),
        ('service', '0008_WyattRemovedAuthorUpdate'),
    ]

    operations = [
    ]
