# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_merge_20161129_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(max_length=100),
        ),
    ]
