# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20161102_1822'),
        ('service', '0007_merge_20161102_0137'),
    ]

    operations = [
    ]
