# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20161128_0334'),
        ('service', '0009_auto_20161128_0434'),
    ]

    operations = [
    ]
