# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_nodemanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='baseUrl',
            new_name='host',
        ),
        migrations.AddField(
            model_name='node',
            name='port',
            field=models.IntegerField(default=80),
        ),
    ]
