# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20161128_2232'),
        ('service', '0010_auto_20161129_0409'),
    ]

    operations = [
    ]
