# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_merge_20161128_0513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NodeManager',
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
