# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20161129_0409'),
        ('service', '0011_auto_20161128_2325'),
    ]

    operations = [
    ]
