# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_merge_20161130_0053'),
        ('service', '0013_merge_20161130_0053'),
    ]

    operations = [
    ]
